# Build settings
remote_theme             : VikasChandrashekar/dactl

# page settings
blog:
  title                      : <dev>to</prod>
  description                : #
# Layout configuration
  logo_path                  : "assets/img/logo.png"
  search_path                : "VikasChandrashekar.github.io"
  hero_layout                : false
  hero_placeholder           : # "assets/img/generic_hero.jpg"
  excerpts                   : true 
  inline_footnotes           : true 
  titles_only                : false 

# Fonts
  font                       : '"Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
  load_google_fonts          : 'Rubik:400,400italic,700,700italic'


# Author info
author:
  fullname                  : Vikas Chandrashekar
  rss                       : false 
  mail                      : vikas.chandrashekar@outlook.com 
  github                    : VikasChandrashekar
  disqus                    : v-ka-s
  google_analytics          : #


